### ISSUE TITLE
RH ET Activity Status doesn't change

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/ngm-reportDesk#32] opened 2022-02-04 04:49 UTC
**Describe the bug**
The "ongoing" status doesn't change to "completed" even though the activity end date has been specified and already passed.

**Context**
This is an issue raised by the ReportHub focal person in Somalia and reported in a call meeting with me on Wed, 03 Feb 2022 at 18.30 (GMT +7).

**To Reproduce**
1. Login using ethiopia account
2. Go to https://reporthub.org/desk/#/cluster/projects/report/61dd22efd19db07354a3cff8/61dd22efd19db07354a3cffc
3. Scroll down to 'Activity End Date'
4. See error where the end date has been specified, and the date has already passed but the status is still ongoing

**Expected behavior**
The platform should generate the status automatically accordingly.

**Screenshots**
<img width="1109" alt="Screen Shot 2022-02-04 at 11 44 51" src="https://user-images.githubusercontent.com/28089698/152473539-305261de-7603-4258-bc96-209446ec1c69.png">

**Additional context**

**Comment by fakhrihawari** [comment] 2022-02-04 07:09
The issue is in directive
Already fixed on this link PR:
https://github.com/iMMAP/ngm-reportHub/pull/113

**Closed as completed** 2022-02-09 10:43 UTC
Labels: bug
